# Generated by Django 5.2 on 2025-05-18 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('receipt_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Error'), (3, 'Processed'), (4, 'Itemised')], default=1)),
                ('sync_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Error'), (3, 'Synced'), (4, 'Deleted')], default=1)),
                ('splitwise_id', models.IntegerField(null=True)),
                ('splitwise_group', models.IntegerField()),
                ('splitwise_paid_by', models.IntegerField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expense')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splitwise_user', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expense')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('splitwise_user', 'expense'), name='user_expense_unique')],
            },
        ),
    ]
