FROM python:3.12-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    tesseract-ocr \
    && rm -rf /var/lib/apt/lists/*
    

# Install Python dependencies
COPY src/backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt gunicorn

# Copy project
COPY src/backend/ .

# Create directories for static and media files
RUN mkdir -p /app/staticfiles /app/mediafiles /app/db_data
 
# Collect static files
RUN python itemyze/manage.py collectstatic --noinput --settings=itemyze.settings.prod