FROM node:23-alpine as build

WORKDIR /app

# Install dependencies
COPY src/frontend/package.json src/frontend/package-lock.json* ./
RUN npm ci

# Copy source code and build
COPY src/frontend/ .
RUN npm run build

CMD ["tail", "-f", "/dev/null"]